dist: bionic
sudo: required
language: node_js
node_js:
- lts/*
install:
- wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
- sudo dpkg -i hugo*.deb
- npm ci
script:
- hugo version
- hugo
before_deploy:
- openssl aes-256-cbc -K $encrypted_426953162b7a_key -iv $encrypted_426953162b7a_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- echo -e "Host ${DEPLOY_HOST}\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
deploy:
  provider: script
  skip-cleanup: true
  script: rsync -r --quiet --delete-after ${TRAVIS_BUILD_DIR}/public/ ${DEPLOY_USER}@${DEPLOY_HOST}:/www/
  on:
    branch: master
env:
  global:
  - PRODUCTION=true
  - HUGO_RELEASE=0.58.3
  - secure: fx95FyhgoI/IEwOxQfNZk5tquQ8YkTxGAA8lBSVoQRjy61WISPZJwd7wUdh4Vhqaf6064DVx2pKUhJNIkqeKxVQler7qzU0VbUv1JBvFlZ8QeiybuKSSOJbNt7C/CXtzZwJ3JpB5JZ+1I2VCtuVq/ogN3smDhJREkCFw1cjFwuj1LlCuTU7ZGIoNAzfgDS1oA80bxv80c/motxG/Bm5lUKF4uHDSmmKX+RvRWUHBenfYCb3CEsW4E2hdPFIrxAKZ8P+Rf9WV1hi0XxTGtajo7zSGLTmuatj9dF05ia22i86+f+RVKEuMp6AhnhaEhsIzfCVSWaiuBzI1kfZ+BTGsKTXaplToysPDxMHOeJXBr/eN0oMwBQOR8PKlvhTAyaIqswvelPLhiqCGmxg8B1GKAAsgj9UG8v6zlMTvVMV5xe55Q2IAXjsqEXABSEwFzDM1bOJd09TqBEm3b4WxIw78b/7p1Y3FEBZjg1CQRhzqRLmeetYx3134UDNncGhx4MF4S9yY+b2UqGi4XVpvPS3/ISqSNElb+7kuKiSQisYCBNvk/zXiWXdRoNaQddj36zpLdZpDU3K7R+OW6t845REREG58n1Y0bRC7nKNOhupUmQZUkA5UUBrdp4TP4IKUCVxEE9RY9U4JOFztd6nl9gXgixBWCIwmLom1ioSYTqAoTu0=
  - secure: bKbVnltZ2IOARb8EuCz7+o5vxa+7mShRQqkyTHLnh7IjyuI1y7EL8Onk2ViRRYDWFU68A+xYMowalhAHgyR9oRDxjUgyNONN8z06JHiERM5h/93RLXyMKLShfsLrvtEHtfU+nfHDs4mlnabUEa7vUr0LsjNjuDEi0WUABeFQYajRcS2SMPt+87UQaonhOSKQS4waIbXE7tWZWvxm5DjWDNQzI8ek5HxaQ9uygYg1vPnobSJ8JCr3ui5wqoy1BmkEFqodoRxPkhIa/WwS25D4OOPkDSZ++DEn3LnUQaZwo7YsETIqnBtACmyJ5cgJSQtDD5yBDrMZh8H2GZAEDwO1lfONzKZyYbNRFJ5fbbfUR0fTmMLCg0QWKWX/qcVVTEJTQkOv6JY+vJLpkdaO6LAooXz6SQQIUfoH16pT/MDNb8XbwyLPahFEXHHILuGDQ2CiS2jgKk7UVDugQzDljSOj25U8Jiaczb+1lHX1HEgC7SmfcUdQ/nS0mnOEsKNT5s9feG/Ctda/s2nPQUUQp5wl1kakMw/C5UljXWjSGR1koXn90W7OGXWP7QtvCtf4c5+wZ24kDt4/Q+wrQk1CXlUYSHnJFlgiFoRuMxsH03QmzDiKGp76WcjEtaxUF5BTqLgrAK1WTV5f4BLJiiBNaGHi7ZZBYlOkjgJp3+3reYmRAB0=
