dist: bionic
sudo: required
language: node_js
node_js:
- lts/*
install:
- wget "https://github.com/gohugoio/hugo/releases/download/v${HUGO_RELEASE}/hugo_extended_${HUGO_RELEASE}_Linux-64bit.deb"
- sudo dpkg -i hugo*.deb
- npm ci
script:
- hugo version
- hugo
env:
  global:
  - PRODUCTION=true
  - HUGO_RELEASE=0.58.3
before_install:
- openssl aes-256-cbc -K $encrypted_426953162b7a_key -iv $encrypted_426953162b7a_iv
  -in deploy_rsa.enc -out deploy_rsa -d
