baseURL = "https://johenker.de/"
disableKinds = ["taxonomy", "taxonomyTerm", "section", "RSS"]
languageCode = "de"
title = "Jo Henker Fotografie"
[[menu.main]]
name = "People"
weight = 1
[[menu.main]]
name = "Transportation"
weight = 2
[[menu.main]]
name = "Projects"
weight = 3
