baseURL = "http://johenker.de/"
disableKinds = ["taxonomy", "taxonomyTerm", "section", "RSS"]
languageCode = "de"
title = "Jo Henker Fotografie"
[[menu.main]]
name = "Eine Gallerie"
url = "/portfolio/gallery1"
weight = 1
